# One polling cycle. run_id is the correlation identifier shared by the poller,
# worker, logs, and status output (§7, §11); it is generated by the database default
# so a row always carries one.
class IngestionRun < ApplicationRecord
  COUNTERS = %i[
    pages_fetched events_received push_events_seen events_created
    duplicates_skipped events_quarantined events_failed
  ].freeze

  # The vocabulary PR 3 deferred here (§13, PR 5's "ingestion run summaries").
  #
  #   running        created before the fetch, completed_at still NULL. A process killed
  #                  mid-run leaves exactly this, which is the honest crash signal — and
  #                  the run row is a summary artifact, not business state: §8's
  #                  durability boundary is the committed push_events row.
  #   completed      a page was fetched and every envelope reached a terminal outcome,
  #                  quarantines and per-event failures included.
  #   not_modified   a 304. §10: no event processing runs and the reservation stays
  #                  debited. Distinct from completed because "the feed had nothing new"
  #                  and "the feed returned an empty page" are different facts.
  #   deferred       the request never happened — a budget denial, a busy gate, or a
  #                  rate-limit response. §10 is explicit that these are not failures, so
  #                  folding them into failed would burn a healthy source's failure count.
  #   failed         the attempt happened and did not produce usable events.
  #
  # There is deliberately no busy status: the run row is created *inside* the source lock,
  # so Errors::SourceBusy provably cannot leave one behind.
  STATUSES = %w[ running completed not_modified deferred failed ].freeze

  # What "Latest successful run" means in the one-shot's state summary (§9). A 304 counts:
  # the poll succeeded and GitHub reported nothing new.
  SUCCESSFUL_STATUSES = %w[ completed not_modified ].freeze

  belongs_to :event_source, inverse_of: :ingestion_runs

  # enum … validate: true matches Enrichable and GithubApiBudget, the two vocabularies
  # already in this codebase. Unlike those two there is no matching CHECK constraint: one
  # needs a migration and PR 3 owns the schema, so the validation is the guard here and the
  # constraint is a one-line follow-up whenever migrations are next touched.
  enum :status, STATUSES.index_by(&:itself), validate: true

  validates :started_at, :status, presence: true
  validates(*COUNTERS, numericality: { greater_than_or_equal_to: 0 })

  scope :successful, -> { where(status: SUCCESSFUL_STATUSES) }
  scope :latest_successful, -> { successful.where.not(completed_at: nil).order(completed_at: :desc) }
end
