# One polling cycle. run_id is the correlation identifier shared by the poller,
# worker, logs, and status output (§7, §11); it is generated by the database default
# so a row always carries one.
#
# The run status vocabulary and the counter semantics land with PR 5's run summaries.
class IngestionRun < ApplicationRecord
  COUNTERS = %i[
    pages_fetched events_received push_events_seen events_created
    duplicates_skipped events_quarantined events_failed
  ].freeze

  belongs_to :event_source, inverse_of: :ingestion_runs

  validates :started_at, :status, presence: true
  validates(*COUNTERS, numericality: { greater_than_or_equal_to: 0 })
end
